### ISSUE TITLE
Cannot connect to iTunes Store

### ISSUE THREAD

**Issue by a-koka** [chirag04/react-native-in-app-utils#117]
Lately I've started receiving a few of the following errors and I'm wondering if I'm losing sales or whether these are just different examples of the user cancelling the purchase or not entering a valid iTunes password.

```
{ code: 'ENSURLERRORDOMAIN-999',
  userInfo:
   { NSErrorFailingURLKey: null,
     NSLocalizedDescription: 'Cannot connect to iTunes Store',
     NSErrorFailingURLStringKey: 'https://p45-buy.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy' },
  message: 'Cannot connect to iTunes Store',
  domain: 'NSURLErrorDomain' }
```

```
{ code: 'ESKERRORDOMAIN0',
  userInfo: { NSLocalizedDescription: 'Cannot connect to iTunes Store' },
  message: 'Cannot connect to iTunes Store',
  domain: 'SKErrorDomain' }
```

**Comment by brianomchugh** [comment]
I have not seen ENSURLERRORDOMAIN-999 yet, but I definitely get ESKERRORDOMAIN0 when a user cancels (and also when a user tries to repurchase something they already own). I ended up having to ignore all errors in my code since it was impossible to figure out what happened from code/message.

**Comment by a-koka** [comment]
Thanks @brianomchugh. Is there any documentation of all these codes? I couldn't find them anywhere.

**Comment by brianomchugh** [comment]
Not sure, but check out #15

**Comment by superandrew213** [comment]
@a-koka where you able to figure out if this error is happening in production too or just for dev/sandbox users?

**Comment by a-koka** [comment]
I should have mentioned. I got the above errors from my production server. I send them over to the server when a device throws a strange error. I haven't seen many of these recently though.

**Comment by talalmajali** [comment]
@a-koka, we're facing a similar thing, where users do have receipts from Apple, but nothing gets fired to our server(the callback of purchasing is not being invoked). But we don't know where the problem is, could you tell us how you 'send them over to the server when a device throws a strange error" ?

**Comment by a-koka** [comment]
I'm catching all unsuccessful attempts whether inside a `catch` or or invalid status codes and then sending them to the server via a custom `logError` API.

The good news is that I haven't seen any such errors in the past 2 months so maybe things were fixed in a recent version.

**Comment by hugoh1995** [comment]
I'm suddenly going through the same issue even tho it workes well before and I havent changed anything.

**Comment by HermitCarb** [comment]
Same issue too.

![image](https://user-images.githubusercontent.com/8078658/40039972-0a12903e-584b-11e8-9cf7-af39d1e6e4f8.png)

But strangely, after I changed a Store account, it worked. 🤷‍♂️
I am going to check the OC code. 😔

**Comment by kawashimaken** [comment]
I also find out today, my sandbox user can purchase, however my TestFlight version still shown "can not connect to iTunes Store" , purchase failed....
